name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  scala_version: '3.3.6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Assemble JAR
        run: sbt test assembly
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/scala-${{ env.scala_version }}/swim-report.jar
